spring.application.name=JwtAssignment

server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT ??
jwt.secret.key=bXlTZWNyZXRLZXlGb3JEZXZlbG9wbWVudFRoYXRTaG91bGRCZUF0TGVhc3QzMkNoYXJhY3RlcnNMb25n
jwt.expiration=7200000

logging.level.com.example=DEBUG
logging.level.org.springframework.security=DEBUG